catName1 = input('Entre o nome do gato 1: ')
catName2 = input('Entre o nome do gato 2: ')
catName3 = input('Entre o nome do gato 3: ')
catName4 = input('Entre o nome do gato 4: ')
catName5 = input('Entre o nome do gato 5: ')
catName6 = input('Entre o nome do gato 6: ')
print('o nome dos gatos é:')
print(f'{catName1}, {catName2}, {catName3}, {catName4}, {catName5}, {catName6}')
